# Generated by Django 5.2.12 on 2026-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperMartapp', '0002_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
